# =============================
# Minimal Hyprlock Config
# =============================

background {
    monitor =
    path = /home/morninginheaven/Wallpapers/wallpaper.jpg
    blur_passes = 3
    blur_size = 8
}

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(ffffffee)
    font_size = 85
    font_family = Inter
    position = 0, 200
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 270, 60
    outline_thickness = 2
    rounding = 14

    dots_size = 0.28
    dots_spacing = 0.2
    dots_center = true

    # Тёмный аккуратный бордер
    outer_color = rgba(2a2a2aff)
    inner_color = rgba(11111bcc)

    font_family = Inter
    font_color = rgba(ffffffee)

    placeholder_text = Password
    placeholder_color = rgba(888888ff)

    fade_on_empty = false

    position = 0, -100
    halign = center
    valign = center
}
